/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vishu tyagi
 */
public class AttendenceList extends javax.swing.JFrame {

    /**
     * Creates new form AttendenceList
     */
    
    static String timein;
       static String timeout;
    public AttendenceList() {
        initComponents();
    }
    
    public Connection getConnection()
        {
           Connection con = null;
    
           try {
              con = DriverManager.getConnection("jdbc:mysql://localhost/staff_management","root","");
            
              return con;
             } catch (SQLException ex) {
               Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
           
              return null;
        }
    
    }
    
    
    public ArrayList<Detail2> getProductList() throws SQLException
    {
    ArrayList<Detail2> productList  = new ArrayList<Detail2>();
    Connection con = getConnection();
    String query = " SELECT * FROM logintable";
    
    Statement st;
    ResultSet rs;
    
    try {
    st=con.createStatement();
    rs = st.executeQuery(query);
    Detail2 product;
    
    while(rs.next())
        
    {
         timein = rs.getString("timein");
         timeout=rs.getString("timeout");
       product = new Detail2(rs.getString("staffid"), timein , timeout ,rs.getString("date")); 
       
    //product = new Details(rs.getString("id"),rs.getString("name"),Float.parseFloat(rs.getString("price")),rs.getString("add_date"),rs.getBytes("image"));
    productList.add(product);
    }
    } catch (SQLException ex) {
               System.out.println(ex.getMessage());
           }
    
        return productList;
        
    }    
    
    // 2- populate the JTable
     
     public void Show_Products_In_JTable()
     {
        try {
            ArrayList<Detail2> list = getProductList();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            //clear jtable content
            model.setRowCount(0);
            Object[] row = new Object[4];
            for(int i = 0; i < list.size(); i++)
            {
                row[0] = list.get(i).getStaffid();
                row[1] = list.get(i).getTimein();
                row[2] = list.get(i).getTimein();
                row[3] = list.get(i).getDate();
                
                
                
                
                model.addRow(row);   
            }  } catch (SQLException ex) {
                System.out.println(ex.getMessage());
        }
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel2.setMaximumSize(new java.awt.Dimension(3277, 357));
        jPanel2.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 102, 255));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "staffid", "timein", "timeout", "date", "total hour"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(290, 120, 586, 402);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Staff Attendencce");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(340, 10, 500, 82);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/backbutton.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 40, 99, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/technology-background-2012.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 1170, 560);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 573));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ControlPanel cp = new ControlPanel();
        cp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendenceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendenceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendenceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendenceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendenceList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
