/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Management;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vishu tyagi
 */
public class LeavePanel extends javax.swing.JFrame {

    /**
     * Creates new form LeavePanel
     */
    public LeavePanel() {
        initComponents();
    }
    
    
    
     public java.sql.Connection getConnection()
    {
    java.sql.Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/staff_management","root","");
           // JOptionPane.showMessageDialog(null,"connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,"not connected");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_LeaveId = new javax.swing.JTextField();
        txt_LeaveName = new javax.swing.JTextField();
        txt_LeaveSubject = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_LeaveMessage = new javax.swing.JTextArea();
        btn_LeaveSend = new javax.swing.JButton();
        btn_LeaveClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 150, 31, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 200, 57, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 250, 70, 22);

        txt_LeaveId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_LeaveId);
        txt_LeaveId.setBounds(180, 150, 96, 28);

        txt_LeaveName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_LeaveName);
        txt_LeaveName.setBounds(180, 200, 180, 28);

        txt_LeaveSubject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_LeaveSubject);
        txt_LeaveSubject.setBounds(180, 250, 459, 28);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Type the message below :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 300, 160, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Message :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 330, 79, 22);

        txt_LeaveMessage.setColumns(20);
        txt_LeaveMessage.setRows(5);
        jScrollPane2.setViewportView(txt_LeaveMessage);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(180, 330, 459, 160);

        btn_LeaveSend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_LeaveSend.setText("Send");
        btn_LeaveSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LeaveSendActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LeaveSend);
        btn_LeaveSend.setBounds(200, 520, 90, 25);

        btn_LeaveClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_LeaveClear.setText("Clear");
        btn_LeaveClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LeaveClearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LeaveClear);
        btn_LeaveClear.setBounds(340, 520, 80, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Leave Application");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 30, 410, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/backbutton.jpg"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 70, 110, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/technology-background-2012.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LeaveSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeaveSendActionPerformed
        try {
           
            
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO chutti(id ,name ,subject ,message ,date) " + " value(?,?,?,?,?)");
                ps.setString(1,txt_LeaveId.getText());
                ps.setString(2,txt_LeaveName.getText());
                 ps.setString(3,txt_LeaveSubject.getText());
                ps.setString(4,txt_LeaveMessage.getText());
                java.sql.Timestamp date= new java.sql.Timestamp(new java.util.Date().getTime());
                ps.setTimestamp(5, date);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Application sucessfully submittted");
             
                
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
           // System.out.println(ex);
        }
    }//GEN-LAST:event_btn_LeaveSendActionPerformed

    private void btn_LeaveClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeaveClearActionPerformed
        // TODO add your handling code here:
        txt_LeaveSubject.setText(null);
        txt_LeaveMessage.setText(null);
    }//GEN-LAST:event_btn_LeaveClearActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here: 
        StaffPanel s= new StaffPanel();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeavePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeavePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeavePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeavePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeavePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LeaveClear;
    private javax.swing.JButton btn_LeaveSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField txt_LeaveId;
    private javax.swing.JTextArea txt_LeaveMessage;
    public static javax.swing.JTextField txt_LeaveName;
    private javax.swing.JTextField txt_LeaveSubject;
    // End of variables declaration//GEN-END:variables
}
