/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Management;

import static Management.AttendenceList.timein;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vishu tyagi
 */
public class StaffPanel extends javax.swing.JFrame {

    /**
     * Creates new form StaffPanel
     */
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String DB_URL = "jdbc:mysql://localhost/staff_management";

   //  Database credentials
   static final String USER = "root";
   static final String PASS = "";
    long totalmin;
   
    public StaffPanel() {
        initComponents();
    }
    
     public java.sql.Connection getConnection()
    {
    java.sql.Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/staff_management","root","");
           // JOptionPane.showMessageDialog(null,"connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,"not connected");
            return null;
        }
    }
    

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTimeOut = new javax.swing.JTextField();
        txtTimeIn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jdtDate = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLbSett = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        totalSec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER YOUR ID:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(610, 260, 162, 25);

        txtId.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId);
        txtId.setBounds(790, 260, 158, 28);

        jLabel3.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIME IN:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(680, 370, 91, 25);

        jLabel4.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIME OUT:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(660, 420, 121, 25);

        txtTimeOut.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeOutActionPerformed(evt);
            }
        });
        txtTimeOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimeOutKeyPressed(evt);
            }
        });
        jPanel2.add(txtTimeOut);
        txtTimeOut.setBounds(790, 420, 158, 28);

        txtTimeIn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtTimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeInActionPerformed(evt);
            }
        });
        jPanel2.add(txtTimeIn);
        txtTimeIn.setBounds(790, 370, 158, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/Button Add23.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(650, 540, 129, 39);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/Button Refresh1.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(900, 540, 131, 39);

        jLabel8.setFont(new java.awt.Font("Vani", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INSTRUCTION :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 420, 250, 41);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("1 :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 470, 26, 17);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fill every detail except time out and press submit button ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 470, 320, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(13, 495, 26, 17);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Then, in departure submit your time out and press button update");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(49, 494, 390, 22);

        jdtDate.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(jdtDate);
        jdtDate.setBounds(790, 310, 160, 30);

        jLabel13.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Select Date :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(640, 320, 115, 31);

        jLabel14.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Hour :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(650, 470, 112, 31);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CHeck time");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16);
        jLabel16.setBounds(980, 370, 90, 28);

        jLbSett.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        jLbSett.setForeground(new java.awt.Color(255, 255, 255));
        jLbSett.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel2.add(jLbSett);
        jLbSett.setBounds(550, 140, 583, 73);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("  CHECK HOUR");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17);
        jLabel17.setBounds(1040, 476, 90, 20);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPanel2.add(txtTotal);
        txtTotal.setBounds(790, 470, 108, 31);

        totalSec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(totalSec);
        totalSec.setBounds(920, 470, 96, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(":");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(900, 460, 17, 40);

        jLabel18.setBackground(new java.awt.Color(0, 51, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Click here for leave application");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18);
        jLabel18.setBounds(23, 562, 240, 17);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/staff attendence.jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 340, 266, 149);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("      Staff Attendence");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(320, 20, 540, 82);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/logout.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 70, 20, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Management/technology-background-2012.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(4, 0, 1150, 600);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1156, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeInActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
            java.sql.Statement stmt = null;
            String id= txtId.getText();
            String timein= txtTimeIn.getText();
            String timeout= txtTimeOut.getText();
            String totalhour = txtTotal.getText();
           /// String totalsec = totalSec.getText();
           // double value = Double.parseDouble(totalsec);
            
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
             String joining_date = dateFormat.format(jdtDate.getDate());
             
             
           
           
            
            
            java.sql.Connection con = getConnection();
            stmt = con.createStatement();
            
                String query1 ="INSERT INTO logintable values('"+id+"','"+timein+"' ,'"+timeout+"','"+joining_date+"','"+totalhour+"','"+totalmin+"')";
                stmt.executeUpdate(query1);
                JOptionPane.showMessageDialog(null,"data sucessfully inserted");
                Login l= new Login();
                l.setVisible(true);
                this.setVisible(false);
                
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          String UpdateQuery = null;
       PreparedStatement ps = null;
       Connection con = getConnection();
        
        try {
               UpdateQuery = "UPDATE logintable SET timeout = ? , totalhour = ?  , totalmin = ? WHERE staffid = ? AND date = ?";
               ps =con.prepareStatement(UpdateQuery);
               
               ps.setString(1,txtTimeOut.getText());
               ps.setString(2,txtTotal.getText());
               //String totalsecond = totalSec.getText();
              // long value = long.parseLong(totalsecond);
               ps.setLong(3,totalmin);
               ps.setString(4,txtId.getText());
               SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String addDate = dateFormat.format(jdtDate.getDate());
                ps.setString(5,addDate);
                 ps.executeUpdate();
                 
                 JOptionPane.showMessageDialog(null,"ATTENDANCE UPDATED");
                 
           } catch (SQLException ex) {
                          JOptionPane.showMessageDialog(null,ex.getMessage());

           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTimeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeOutActionPerformed

    private void txtTimeOutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeOutKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimeOutKeyPressed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        try {
            String id= txtId.getText();
            java.sql.Statement stmt = null;
            
            java.sql.Connection con = getConnection();
            stmt = con.createStatement();
            
            String str= "SELECT timein FROM logintable where staffid = '" + id + "'";
             ResultSet RS = stmt.executeQuery(str);
             
              if(RS.next())
              {
              String  timein  = RS.getString("timein");
              System.out.println(timein);
              txtTimeIn.setText(timein);
              }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
        

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here
         try {
            String time1= txtTimeIn.getText();
            String time2= txtTimeOut.getText();
            SimpleDateFormat format = new SimpleDateFormat("HH:mm");
            Date x = format.parse(time1);
            Date y = format.parse(time2);
            long diff = y.getTime() - x.getTime();
            long totalsec=diff/1000;
            totalmin=totalsec/60;
            String str2 = Long.toString(totalmin);
            System.out.println(totalmin);
            long diffMinutes = diff / (60 * 1000) % 60;
            long diffHours = diff / (60 * 60 * 1000) % 12;
          // int difference = (int)((y.getTime() - x.getTime()) / 3600000L);
            
           // String str= String.valueOf(difference);
            String str = Long.toString(diffMinutes);
             String str1 = Long.toString(diffHours);
            System.out.println(diffHours +":"+diffMinutes);
            totalSec.setText(str2);
            txtTotal.setText(diffHours +":"+diffMinutes);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        String name =  jLbSett.getText();
        name = name.replace("WELCOME", "");
        String id = txtId.getText();
        LeavePanel LP =new LeavePanel();
        LP.txt_LeaveName.setText(name);
        LP.txt_LeaveId.setText(id);
        LP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLbSett;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdtDate;
    private javax.swing.JTextField totalSec;
    public static javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTimeIn;
    private javax.swing.JTextField txtTimeOut;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
